version: '2'
services:
  etcd:
    image: nginx
    container_name: nginx-lb
    hostname: nginx-lb
    volumes:
    - /root/kubernetes-ha/nginx-lb/nginx-lb.conf:/etc/nginx/nginx.conf
    ports:
    - 6443:6443
    restart: always

