apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-node-test-1
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: hello-node
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
        role: master
        tier: backend
    spec:
      containers:
      - name: hello-node
        image: vwarship/hello-world:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-test-1
  labels:
    app: hello-node
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: hello-node
    role: master
    tier: backend